# Generated by Django 4.2.4 on 2023-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_rollnumber_alter_users_username'),
        ('subjects', '0002_alter_subjects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='user_id',
            field=models.ManyToManyField(null=True, to='users.users'),
        ),
    ]
