# Generated by Django 4.2.4 on 2023-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.SmallIntegerField(max_length=2),
        ),
    ]
