# Generated by Django 4.2.4 on 2023-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.IntegerField(),
        ),
    ]
