# Generated by Django 4.2.4 on 2023-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
