# Generated by Django 4.2.4 on 2023-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_rollnumber_alter_users_username'),
        ('classes', '0004_alter_classes_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='user_id',
            field=models.ManyToManyField(null=True, to='users.users'),
        ),
    ]
