# Generated by Django 4.2.4 on 2023-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_gender'),
        ('classes', '0005_classes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='user_id',
            field=models.ManyToManyField(to='users.users'),
        ),
    ]
