# Generated by Django 4.2.4 on 2023-08-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='owner_id',
        ),
    ]
