# Generated by Django 4.2.4 on 2023-08-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('users', '0003_remove_users_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='class_id',
            field=models.ManyToManyField(to='classes.classes'),
        ),
        migrations.AddField(
            model_name='users',
            name='subject_id',
            field=models.ManyToManyField(to='subjects.subjects'),
        ),
    ]
