# Generated by Django 4.2.4 on 2023-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_class_id_users_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rollnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
