# Generated by Django 4.2.4 on 2023-09-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classes_user_id'),
        ('subjects', '0004_alter_subjects_user_id'),
        ('users', '0006_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='class_id',
            field=models.ManyToManyField(blank=True, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='users',
            name='subject_id',
            field=models.ManyToManyField(blank=True, to='subjects.subjects'),
        ),
    ]
