# Generated by Django 4.2.4 on 2023-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_gender_alter_users_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rollnumber',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
